/*
 * generated source file
 * do not edit this file
 *
 * modify class 'at.freebim.db.webapp.JsCreator' instead.
 */


at.freebim.db.rest.RestFields = {
	BSDD : 	"b",
	CODE : 	"c",
	COMMENT : 	"cm",
	COMPONENT : 	"co",
	CRAFT : 	"cr",
	DESC : 	"d",
	DISCIPLINE : 	"di",
	DATATYPE : 	"dt",
	GROUP : 	"g",
	GROUP_MEMBER : 	"gm",
	ID : 	"i",
	LEVEL : 	"lv",
	LAW : 	"la",
	MEASURE : 	"me",
	NAME : 	"n",
	NEXT : 	"nx",
	ORDERING : 	"o",
	PARAMETER : 	"pa",
	PHASE : 	"ph",
	PREV : 	"pv",
	PSET : 	"ps",
	ROW : 	"r",
	RESULT : 	"re",
	RESTRICTED : 	"rs",
	REGEXP : 	"rx",
	STATUS : 	"s",
	TIMESTAMP : 	"t",
	TYPE : 	"ty",
	UUID : 	"u",
	UNIT : 	"un",
	VERSION : 	"vs"
};
